#!/usr/bin/env bash

PACKAGE_NAME="tmux-cssh"

# Get new version-number
buildNr=$(cat tmux-cssh/DEBIAN/control | grep "Version" | cut -d " " -f 2)

# Build packages
echo "* Build package ..."
dpkg -b ./${PACKAGE_NAME} deb-packages/${PACKAGE_NAME}_${buildNr}.deb
echo

echo "* Build md5sum-file ..."
md5sum deb-packages/${PACKAGE_NAME}_${buildNr}.deb > deb-packages/${PACKAGE_NAME}_${buildNr}.deb.md5sum
echo

echo "Finished."
echo


